import type { Localized } from '../../../.storybook/locale';
import type { Chapter, VideoPlayerLabels } from './VideoPlayer';

/*
 * Example labels (four Storybook languages), chapters and captions for
 * stories, tests and page prototypes. Not exported from the package.
 */

const deNumber = (n: number) => n.toLocaleString('de-DE');

export const VIDEO_LABELS: VideoPlayerLabels = {
    play: 'Abspielen',
    pause: 'Pause',
    replay: 'Nochmal ansehen',
    back10: '10 Sekunden zurück',
    forward10: '10 Sekunden vor',
    mute: 'Stumm',
    unmute: 'Ton an',
    volume: 'Lautstärke',
    seek: 'Position im Video',
    timeOf: (a, b) => `${a} von ${b}`,
    settings: 'Einstellungen',
    speed: 'Geschwindigkeit',
    speedValue: (r) => (r === 1 ? 'Normal' : `${deNumber(r)}×`),
    captions: 'Untertitel',
    captionsOff: 'Aus',
    pictureInPicture: 'Bild im Bild',
    fullscreen: 'Vollbild',
    exitFullscreen: 'Vollbild beenden',
    chapters: 'Kapitel',
    loading: 'Video lädt …',
    errorTitle: 'Dieses Video konnte nicht geladen werden',
    errorBody: 'Der Link ist möglicherweise abgelaufen. Versuche es erneut.',
    retry: 'Erneut versuchen',
    upNext: 'Als Nächstes',
    playNext: 'Nächste Lektion',
    cancel: 'Abbrechen',
    startsIn: (s) => `Startet in ${s} s`,
    skipped: (s) => (s < 0 ? `${-s} Sekunden zurück` : `${s} Sekunden vor`),
    announce: {
        playing: 'Wiedergabe',
        paused: 'Pausiert',
        seeked: (t) => `Bei ${t}`,
        speed: (r) => `Geschwindigkeit ${r}`,
        volume: (p) => `Lautstärke ${p} %`,
        muted: 'Stumm',
        unmuted: 'Ton an',
        captionsOn: (l) => `Untertitel: ${l}`,
        captionsOff: 'Untertitel aus',
    },
};

export const VIDEO_LABELS_BY_LOCALE: Localized<VideoPlayerLabels> = {
    de: VIDEO_LABELS,
    en: {
        play: 'Play',
        pause: 'Pause',
        replay: 'Watch again',
        back10: 'Back 10 seconds',
        forward10: 'Forward 10 seconds',
        mute: 'Mute',
        unmute: 'Unmute',
        volume: 'Volume',
        seek: 'Position in video',
        timeOf: (a, b) => `${a} of ${b}`,
        settings: 'Settings',
        speed: 'Speed',
        speedValue: (r) => (r === 1 ? 'Normal' : `${r}×`),
        captions: 'Captions',
        captionsOff: 'Off',
        pictureInPicture: 'Picture in picture',
        fullscreen: 'Full screen',
        exitFullscreen: 'Exit full screen',
        chapters: 'Chapters',
        loading: 'Video loading …',
        errorTitle: 'This video could not be loaded',
        errorBody: 'The link may have expired. Please try again.',
        retry: 'Try again',
        upNext: 'Up next',
        playNext: 'Next lesson',
        cancel: 'Cancel',
        startsIn: (s) => `Starts in ${s} s`,
        skipped: (s) => (s < 0 ? `${-s} seconds back` : `${s} seconds forward`),
        announce: {
            playing: 'Playing',
            paused: 'Paused',
            seeked: (t) => `At ${t}`,
            speed: (r) => `Speed ${r}`,
            volume: (p) => `Volume ${p} %`,
            muted: 'Muted',
            unmuted: 'Sound on',
            captionsOn: (l) => `Captions: ${l}`,
            captionsOff: 'Captions off',
        },
    },
    ar: {
        play: 'تشغيل',
        pause: 'إيقاف مؤقت',
        replay: 'المشاهدة مرة أخرى',
        back10: 'رجوع 10 ثوانٍ',
        forward10: 'تقديم 10 ثوانٍ',
        mute: 'كتم الصوت',
        unmute: 'تشغيل الصوت',
        volume: 'مستوى الصوت',
        seek: 'الموضع في الفيديو',
        timeOf: (a, b) => `${a} من ${b}`,
        settings: 'الإعدادات',
        speed: 'السرعة',
        speedValue: (r) => (r === 1 ? 'عادية' : `${r}×`),
        captions: 'الترجمة',
        captionsOff: 'إيقاف',
        pictureInPicture: 'صورة داخل صورة',
        fullscreen: 'ملء الشاشة',
        exitFullscreen: 'الخروج من ملء الشاشة',
        chapters: 'الفصول',
        loading: 'جارٍ تحميل الفيديو …',
        errorTitle: 'تعذّر تحميل هذا الفيديو',
        errorBody: 'ربما انتهت صلاحية الرابط. حاول مرة أخرى.',
        retry: 'حاول مرة أخرى',
        upNext: 'التالي',
        playNext: 'الدرس التالي',
        cancel: 'إلغاء',
        startsIn: (s) => `يبدأ خلال ${s} ث`,
        skipped: (s) => (s < 0 ? `رجوع ${-s} ثوانٍ` : `تقديم ${s} ثوانٍ`),
        announce: {
            playing: 'قيد التشغيل',
            paused: 'متوقف مؤقتًا',
            seeked: (t) => `عند ${t}`,
            speed: (r) => `السرعة ${r}`,
            volume: (p) => `مستوى الصوت ${p} %`,
            muted: 'الصوت مكتوم',
            unmuted: 'الصوت يعمل',
            captionsOn: (l) => `الترجمة: ${l}`,
            captionsOff: 'الترجمة متوقفة',
        },
    },
    tr: {
        play: 'Oynat',
        pause: 'Duraklat',
        replay: 'Tekrar izle',
        back10: '10 saniye geri',
        forward10: '10 saniye ileri',
        mute: 'Sesi kapat',
        unmute: 'Sesi aç',
        volume: 'Ses düzeyi',
        seek: 'Videodaki konum',
        timeOf: (a, b) => `${a} / ${b}`,
        settings: 'Ayarlar',
        speed: 'Hız',
        speedValue: (r) => (r === 1 ? 'Normal' : `${r}×`),
        captions: 'Altyazı',
        captionsOff: 'Kapalı',
        pictureInPicture: 'Resim içinde resim',
        fullscreen: 'Tam ekran',
        exitFullscreen: 'Tam ekrandan çık',
        chapters: 'Bölümler',
        loading: 'Video yükleniyor …',
        errorTitle: 'Bu video yüklenemedi',
        errorBody: 'Bağlantının süresi dolmuş olabilir. Lütfen tekrar dene.',
        retry: 'Tekrar dene',
        upNext: 'Sıradaki',
        playNext: 'Sonraki ders',
        cancel: 'İptal',
        startsIn: (s) => `${s} sn içinde başlıyor`,
        skipped: (s) => (s < 0 ? `${-s} saniye geri` : `${s} saniye ileri`),
        announce: {
            playing: 'Oynatılıyor',
            paused: 'Duraklatıldı',
            seeked: (t) => `${t} konumunda`,
            speed: (r) => `Hız ${r}`,
            volume: (p) => `Ses düzeyi %${p}`,
            muted: 'Ses kapalı',
            unmuted: 'Ses açık',
            captionsOn: (l) => `Altyazı: ${l}`,
            captionsOff: 'Altyazı kapalı',
        },
    },
};

/** Chapters of the 40-second sample video. */
export const SAMPLE_CHAPTERS: Chapter[] = [
    { start: 0, title: 'Einführung' },
    { start: 8, title: 'Alif — der erste Buchstabe' },
    { start: 20, title: 'Ba und Ta' },
    { start: 32, title: 'Zusammenfassung' },
];

export const SAMPLE_CAPTIONS = [
    { src: 'media/sample-lesson.de.vtt', srcLang: 'de', label: 'Deutsch', default: true },
    { src: 'media/sample-lesson.en.vtt', srcLang: 'en', label: 'English' },
];
